app/src/Entity/Booking.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Entity\Traits\DateTimeTrait;
use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 */
class Booking
{
    use DateTimeTrait;

    /**
     * @ORM\Id
     *
     * @ORM\GeneratedValue
     *
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTime $dateStartAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     *
     * @ORM\JoinColumn(nullable=false)
     */
    private ?User $lodger;

    /**
     * @ORM\ManyToOne(targetEntity=StorageSpace::class, inversedBy="bookings")
     *
     * @ORM\JoinColumn(nullable=false)
     */
    private ?StorageSpace $storageSpace;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTime $dateEndAt;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private ?bool $finish = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $pay = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $checkForPayement = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $stripeSessionId;

    public function getId(): int
    {
        return $this->id;
    }

    public function getDateStartAt(): ?\DateTime
    {
        return $this->dateStartAt;
    }

    public function setDateStartAt(?\DateTime $dateStartAt): self
    {
        $this->dateStartAt = $dateStartAt;

        return $this;
    }

    public function getLodger(): ?User
    {
        return $this->lodger;
    }

    public function setLodger(?User $lodger): self
    {
        $this->lodger = $lodger;

        return $this;
    }

    public function getStorageSpace(): ?StorageSpace
    {
        return $this->storageSpace;
    }

    public function setStorageSpace(?StorageSpace $storageSpace): self
    {
        $this->storageSpace = $storageSpace;

        return $this;
    }

    public function getDateEndAt(): ?\DateTime
    {
        return $this->dateEndAt;
    }

    public function setDateEndAt(?\DateTime $dateEndAt): self
    {
        $this->dateEndAt = $dateEndAt;

        return $this;
    }

    public function getFinish(): ?bool
    {
        return $this->finish;
    }

    public function setFinish(?bool $finish): self
    {
        $this->finish = $finish;

        return $this;
    }

    public function getPay(): ?bool
    {
        return $this->pay;
    }

    public function setPay(bool $pay): self
    {
        $this->pay = $pay;

        return $this;
    }

    public function getCheckForPayement(): ?bool
    {
        return $this->checkForPayement;
    }

    public function setCheckForPayement(bool $checkForPayement): self
    {
        $this->checkForPayement = $checkForPayement;

        return $this;
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripeSessionId;
    }

    public function setStripeSessionId(?string $stripeSessionId): self
    {
        $this->stripeSessionId = $stripeSessionId;

        return $this;
    }
}

app/src/Entity/Traits/DateTimeTrait.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity\Traits;

use Doctrine\ORM\Mapping as ORM;

trait DateTimeTrait
{
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTime $created_at = null;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTime $updated_at = null;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTime $deleted_at = null;

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTime
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTime $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * @ORM\PrePersist
     *
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt((new \DateTime('now'))->setTimezone(new \DateTimeZone('UTC')));
        if (null === $this->getCreatedAt()) {
            $this->setCreatedAt((new \DateTime('now'))->setTimezone(new \DateTimeZone('UTC')));
        }
    }

    public function isDeleted(): bool
    {
        return null !== $this->getDeletedAt();
    }
}

app/src/Form/BookingType.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            // ->add('dateStartAt', DateType::class)
            ->add('dateStartAt', DateType::class, [
                // 'widget' => 'single_text',
                'widget' => 'choice',
                // 'html5' => false
                'days' => range(date('d'), date('d') + 7),
                'months' => [date('m')],
                'years' => [date('y')],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

app/src/Controller/BookingController.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\User;
use App\Form\BookingFinishType;
use App\Form\BookingType;
use App\Manager\BookingManager;
use App\Repository\BookingRepository;
use App\Repository\StorageSpaceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Stripe\Stripe;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    /**
     * TODO : A mettre pour un admin.
     *
     * @Route("/booking", name="booking_all")
     */
    public function get_all_booking(BookingRepository $bookingRepository): Response
    {
        return $this->render('pages/booking/list.html.twig', [
            'bookings' => $bookingRepository->findAll(),
        ]);
    }

    /**
     * @Route("/booking/{id}", name="booking_one_for_user", requirements={"id": "\d+"}, methods={"GET"})
     */
    public function get_one_booking_for_user(Booking $booking): Response
    {
        if (!$this->getUser() || $this->getUser() !== $booking->getLodger()) {
            return $this->redirectToRoute('storage_space_all');
        }

        $this->denyAccessUnlessGranted('edit', $booking);

        return $this->render('pages/booking/detail.html.twig', [
            'booking' => $booking,
        ]);
    }

    /**
     * rediriger vers stripe pour le paiement.
     *
     * @Route("/booking/add/storageSpace/{id}", name="booking_add", requirements={"id": "\d+"})
     */
    public function create_booking(
        int $id,
        StorageSpaceRepository $storageSpaceRepository,
        Request $request,
        BookingManager $bookingManager
    ): Response {
        /** @var User|null */
        $user = $this->getUser();

        if (!$user) {
            // Stocker l'URL d'origine dans la session
            $request->getSession()->set('_security.main.target_path', $request->getUri());

            // Redirection vers login
            return $this->redirectToRoute('app_login');
        }

        $booking = new Booking();

        $storageSpace = $storageSpaceRepository->findOneStorage($id);

        $formBooking = $this->createForm(BookingType::class, $booking);

        $formBooking->handleRequest($request);

        if ($formBooking->isSubmitted() && $formBooking->isValid()) {
            return $bookingManager->createdBooking($booking, $storageSpace, $user);
        }

        return $this->render('pages/booking/create.html.twig', [
            'formBooking' => $formBooking->createView(),
            'storageSpace' => $storageSpace,
            'oneBookingTrue' => $bookingManager->verifBookingTrue($user),
        ]);
    }

    /**
     * @Route("/booking/user", name="booking_for_user")
     */
    public function get_all_booking_for_user(
        BookingManager $bookingManager
    ): Response {
        /** @var User|null */
        $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('storage_space_all');
        }

        return $this->render('pages/booking/list_to_user.html.twig', [
            'bookings' => $bookingManager->getAllBookingsForUser($user),
        ]);
    }

    /**
     * TODO : A supprimer.
     *
     * N'est pas utiliser, comme stripe s'occupe de finir une reservation
     *
     * @Route("/booking/form/finish/{id}", name="booking_finish")
     */
    public function get_form_booking_finish(Booking $booking, Request $request, EntityManagerInterface $manager): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('storage_space_all');
        }

        $this->denyAccessUnlessGranted('show', $booking);

        $formBooking = $this->createForm(BookingFinishType::class, $booking);

        $formBooking->handleRequest($request);

        if ($formBooking->isSubmitted() && $formBooking->isValid()) {
            /* $booking->setCreatedAt(new \DateTime())
                ->setLodger($this->getUser())
            ; */

            $manager->persist($booking);
            $manager->flush();

            return $this->redirectToRoute('storage_space_all');
        }

        return $this->render('pages/booking/finish.html.twig', [
            'formBooking' => $formBooking->createView(),
        ]);
    }

    /**
     * @Route("/booking/delete/{id}", name="booking_delete", requirements={"id": "\d+"})
     */
    public function delete_booking(
        Booking $booking,
        BookingManager $bookingManager,
        Request $request
    ): Response {
        /** @var User|null */
        $user = $this->getUser();

        /** @var string|null */
        $token = $request->get('_token');

        if (!$user || null === $token) {
            return $this->redirectToRoute('storage_space_all');
        }

        $this->denyAccessUnlessGranted('delete', $booking);

        if ($this->isCsrfTokenValid('delete', $token)) {
            $bookingManager->deleteBooking($booking);
        }

        return $this->redirectToRoute('booking_for_user');
    }
}

app/templates/pages/booking/create.html.twig
{% extends "base.html.twig" %}

{% block title %}Faire une réservation{% endblock %}

{% block javascrpit2 %}
    <script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block body %}
<div class="container">

    <h1>{{ block('title') }}</h1>

    {% if oneBookingTrue == true %}
        <p>Il est possible de souscrire qu'à un seul abonnement </p>
        <p>Vous avez un abonnement déjà en cours</p>
    {% endif %}

    <div class="one_storage_space">

        {% if storageSpace.images %}
            <img class="img_storage_page_get_all img_storage_page_get_all_2500 img_storage_page_get_one " src= "{{ asset('/uploads/images/' ~ storageSpace.images) }}" alt="" > 
        {% else %}
            <img class="img_storage_page_get_all img_storage_page_get_all_2500 img_storage_page_get_one " src= "{{ asset('/uploads/default/default.jpg') }}" alt="" > 
        {% endif %}

        <div class="description">
            <h3>{{storageSpace.title }}</h3>
            <h4>{{storageSpace.space }} m2</h4>
            <h5>{{ storageSpace.priceByMonth  / 100 | number_format(2, '.', ' ') }} €/mois</h5>
        </div>
    </div>

    {% if oneBookingTrue != true %}

        {{ form_start(formBooking, { 'attr' : { 'class' : 'container_form ' }} ) }}

            <div class="div_form">

                <label for="inputTitle"class='form_label'>Date de réservation : </label>

                <div>
                    {{ form_widget(formBooking.dateStartAt, {attr : 
                        {
                            class : ' js-datepicker form_input',

                        }} ) }}
                </div>
                
                <small class="error_input_small">{{ form_errors(formBooking.dateStartAt) }} </small>

            </div>
            <input type='hidden' name='storage' value="{{ storageSpace.id }}" id='storage'>

            <button type='submit' class="btn" >Reserver </button>
        
        {{ form_end(formBooking) }}

    {% endif %}
</div>
{% endblock body %}

app/templates/pages/booking/detail.html.twig
{% extends "base.html.twig" %}


{% block title %}Voir ma réservation{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {#{{ encore_entry_link_tags('app') }}#}
    {# {% set asset_url  = '/css/main.css' %}
    <link rel="stylesheet" href="{{ asset_url }}" type="text/css" /> #}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block javascrpit2 %}
    <script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block body %}

<div class="container">
    <section>
        <h1>{{ block('title') }}</h1>

        <table class="table table-responsive">
            <thead>
                <tr>
                    <th scope="col">Nom du produit</th>
                    <th scope="col">Adresse complet du produit</th>
                    <th scope="col">Type du produit</th>
                    <th scope="col">espace du produit</th>
                    <th scope="col">Propriétaire du produit</th>
                    <th scope="col">Prix/mois du produit</th>
                    <th scope="col">Date de création de la réservation</th>
                    <th scope="col">Date du début de la réservation</th>
                    {# <th scope="col">Date de fin de la réservation</th> #}
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            

            <tbody>

                <tr>
                    <td data-title="Nom du produit" class="responsive_td_name_produit">{{ booking.storageSpace.title }}</td>
                    <td data-title="Adresse complet du produit">
                        {{ booking.storageSpace.adresse }}
                        {{ booking.storageSpace.postalCode }}
                        {{ booking.storageSpace.city }}
                    </td>
                    <td data-title="Type du produit">{{ booking.storageSpace.category.name }}</td>
                    <td data-title="Espace du produit">{{ booking.storageSpace.space }} m2</td>
                    <td data-title="Propriétaire du produit">
                        {{ booking.storageSpace.owner.firstName }}
                        {{ booking.storageSpace.owner.lastName }}
                    </td>
                    <td data-title="Prix/mois du produit">{{ booking.storageSpace.priceByMonth  / 100 | number_format(2, '.', ' ') }} €/mois</td>
                    <td data-title="Date de création de la réservation">{{ booking.createdAt | date('d/m/Y H:i') }}</td>
                    <td data-title="Date du début de la réservation">{{ booking.dateStartAt | date('d/m/Y') }}</td>

                    {% if booking.dateEndAt %}
                        {# <td data-title="Date de fin de la réservation">{{ booking.dateEndAt | date('d/m/Y') }}</td> #}
                    {% else %}
                            {# <td data-title="Date de fin de la réservation"></td> #}
                    {% endif %}

                    {% if booking.pay == false %}
                        <input type='hidden' name='price' value="{{ booking.storageSpace.priceByMonth }}" id='price'>
                        <input type='hidden' name='booking' value="{{ booking.id }}" id='booking'>
                        <input type='hidden' name='storage' value="{{ booking.storageSpace.id }}" id='storage'>
                        <td><button id="checkout-button" class='btn_pay_or_cancel_booking'>Payer</button></td>
                    {% endif %}

                    {# 
                        si la date du jour n'est pas égale ou n'a pas encore dépassé la date de début de la réservation, 
                        et que le storage est encore disponible,
                        ou que la réservation n'est pas encore payé
                        on permet la suppréssion de cette réservation,
                        passé la date, l'user ne pourra plus supprimer la réservation   
                    #}
                    {% if booking.storageSpace.available == true %}

                        {% if booking.dateStartAt > date() or booking.pay == false %}
                            <td>
                                <form method="POST" action="{{ path('booking_delete', { 'id' : booking.id }) }}" class="middle" onsubmit="return confirm('Etes-vous sur de vouloir annuler votre réservation ?')">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete') }}">
                                    <button class='btn_pay_or_cancel_booking'> Annuler</button>
                                </form>
                            </td>
                        {% endif %}
                        
                    {% endif %}
                    
                </tr>
            </tbody>
        </table>
    </section>
</div>
{% endblock %}


{#  POUR ABONNEMENT #}

{% block script %}

<script type="text/javascript">

    var storage = document.getElementById("storage");
    var booking = document.getElementById("booking");
    var PriceId = document.getElementById("price");

    var stripe = Stripe("pk_test_51IWMatFt4LI0nktGFU4LeoUDWwAX14vyTzFYMWPd11q7ohJjoeFOoSCe6FeSVa5QigzkorWp5dqTe9VqjswDRwll00c5dMrO46");
  

    // Créer une session de paiement avec l'ID de plan sélectionné
    var createCheckoutSession = function(priceId) {
        return fetch("/commande/create-checkout-session/" + storage.value + "/" + booking.value, {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                priceId: priceId
            })
        }).then(function(result) {
            return result.json();
        });
    };

    document
    .getElementById("checkout-button")
    .addEventListener("click", function(evt) {
        createCheckoutSession(PriceId.value).then(function(data) {
        // Call Stripe.js method to redirect to the new Checkout page
        stripe
            .redirectToCheckout({
            sessionId: data.id
            })
            .then(handleResult);
        });
    });
      
</script>

{% endblock %}

{#  POUR PAYEMENT UNIQUE

{% block script %}
    <script type="text/javascript">
    
        var storage = document.getElementById("storage");
        console.log(storage.value);
        var booking = document.getElementById("booking");
        console.log(booking.value);
        // Create an instance of the Stripe object with your publishable API key
        {# var stripe = Stripe("pk_test_TYooMQauvdEDq54NiTphI7jx"); # }
        var stripe = Stripe("pk_test_51IWMatFt4LI0nktGFU4LeoUDWwAX14vyTzFYMWPd11q7ohJjoeFOoSCe6FeSVa5QigzkorWp5dqTe9VqjswDRwll00c5dMrO46");
        var checkoutButton = document.getElementById("checkout-button");
        checkoutButton.addEventListener("click", function () {
            fetch("/commande/create-session/"+ storage.value + "/" + booking.value , {
                method: "POST",
            })
            .then(function (response) {
                return response.json();
                //console.log(response.text());
            })
            .then(function (session) {
                console.log(session);
                if(session.error == 'not_storage'){
                    window.location.replace(' {{ path("storage_space_all") }} ')
                }else{
                    return stripe.redirectToCheckout({ sessionId: session.id });
                }
                
            })
            .then(function (result) {
                // If redirectToCheckout fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using error.message.
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.log(error);
                console.error("Error:", error);
            });
        });
    </script>

{% endblock %} 
#}

app/templates/pages/booking/finish.html.twig
{% extends "base.html.twig" %}

{% block title 'Fermer une reservation' %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block body %}
<div class="form_container">

    <h1>Fermer une reservation</h1>

    {{ form_start(formBooking, { 'attr' : { 'class' : 'form' }} ) }}

        <div class="form_group">

            <div class="form-error">
                {{ form_errors(formBooking.dateEndAt) }}
            </div>

            <label for="inputTitle">Date de fin de réservation : </label>

            <div>
                {{ form_widget(formBooking.dateEndAt, {attr : 
                    {
                        class : 'form_control js-datepicker',

                    }} ) }}
            </div>
            
            <small>{{ form_errors(formBooking.dateEndAt) }} </small>

        </div>
        
        <button type="submit" class="btn_submit">Fermer la Réservation</button>

    {{ form_end(formBooking) }}
</div>
{% endblock body %}

app/templates/pages/booking/list_to_user.html.twig
{% extends "base.html.twig" %}

{% block title 'Voir tous mes transactions' %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block body %}

<div class="container">

    <section>
        <h1>Voir tous mes transactions</h1>

        <table class="table table-responsive">
            <thead>
                <tr>
                    <th scope="col">Nom du produit</th>
                    <th scope="col">Adresse complet du produit</th>
                    <th scope="col">Type du produit</th>
                    <th scope="col">espace du produit</th>
                    <th scope="col">Propriétaire du produit</th>
                    <th scope="col">Prix/mois du produit</th>
                    <th scope="col">Date de création de la réservation</th>
                    <th scope="col">Date du début de la réservation</th>
                    <th scope="col">Date de fin de la réservation</th>
                    {# <th></th> #}
                </tr>
            </thead>

            <tbody>
                {% for booking in bookings %}
                     
                    <tr>
                        <td data-title="Nom du produit" class="responsive_td_name_produit">{{ booking.storageSpace.title }}</td>
                        <td data-title="Adresse complet du produit">
                            {{ booking.storageSpace.adresse }}
                            {{ booking.storageSpace.postalCode }}
                            {{ booking.storageSpace.city }}
                        </td>
                        <td data-title="Type du produit">{{ booking.storageSpace.category.name }}</td>
                        <td data-title="Espace du produit">{{ booking.storageSpace.space }} m2</td>
                        <td data-title="Propriétaire du produit">
                            {{ booking.storageSpace.owner.firstName }}
                            {{ booking.storageSpace.owner.lastName }}
                        </td>
                        <td data-title="Prix/mois du produit">{{ booking.storageSpace.priceByMonth  / 100 | number_format(2, '.', ' ') }} €/mois</td>
                        <td data-title="Date de création de la réservation">{{ booking.createdAt | date('d/m/Y H:i') }}</td>
                        <td data-title="Date du début de la réservation">{{ booking.dateStartAt | date('d/m/Y') }}</td>

                        {% if booking.dateEndAt %}
                            <td data-title="Date de fin de la réservation">{{ booking.dateEndAt | date('d/m/Y') }}</td>
                        {% else %}
                               {# <td data-title="Date de fin de la réservation"></td> #}
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
</div>    

{% endblock body %}